# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
          ssh-key: ${{ secrets.SSH_KEY }}
          repository: Mustafakhn/private-action
          path: ./.github/actions/private-action
    - name: Run a multi-line script
      run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          gh pr view --repo ${{ env.REPO }} ${{ env.PR_NUM }} --json title | grep -P "title" | cut -d ' ' -f 1 | sed 's/{"title":"//'
    - run: gh pr view --json title | cut -d ' ' -f 1 | sed 's/{"title":"//'
    - uses: ./.github/actions/private-action
# test
