name: test-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test-after-deploying-to-default-with-curl:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: health-check-with-curl
      uses: Mustafakhn/health-check-action@main
      with:
          website_url: https://full-cicd.uc.r.appspot.com/
          version_name: version
          method: curl
  test-after-deploying-to-default-with-wget: 
    
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-curl ]
    if: failure()
    
    steps:
    - name: health-check-with-wget
      uses: Mustafakhn/health-check-action@main
      with:
          website_url: https://full-cicd.uc.r.appspot.com/
          version_name: version
          method: wget
          
  notification-failure:
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-wget ]
    if: failure()
    
    steps:
      - name: failure-message
        run: echo "failure"
          
    
  notification-success:
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-curl,test-after-deploying-to-default-with-wget ]
    if: (needs.test-after-deploying-to-default-with-curl.result == 'success' && needs.test-after-deploying-to-default-with-curl.result == 'skipped') || (needs.test-after-deploying-to-default-with-curl.result == 'failure' && needs.test-after-deploying-to-default-with-curl.result == 'success')
    steps:
    - name: success-message
      run: echo "success"
