name: test-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test-after-deploying-to-default-with-curl:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: health-check-with-curl
#       uses: Mustafakhn/health-check-action@main
#       with:
#           website_url: https://abc-full-cicd.uc.r.appspot.com/
#           version_name: version
#           method: curl
      run: wget https://abc-full-cicd.uc.r.appspot.com/
          
  notification:
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-curl ]
    if: success()
    steps:
    - name: success-message
      run: echo "success"

  test-after-deploying-to-default-with-wget: 
  
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-curl ]
    if: (needs.test-after-deploying-to-default-with-wget.result == 'failure')
    
    steps:
    - name: health-check-with-wget
#       uses: Mustafakhn/health-check-action@main
#       with:
#           website_url: https://full-cicd.uc.r.appspot.com/
#           version_name: version
#           method: wget
      run: wget https://full-cicd.uc.r.appspot.com/
          
  notification-success:
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-wget ]
    if: success()
    steps:
    - name: success-message
      run: echo "success"
  
  notification-failure:
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-wget ]
    if: failure()
    
    steps:
      - name: failure-message
        run: echo "failure"
          
