name: test-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test-after-deploying-to-default-with-curl:
    
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.test.outputs.test }}
    steps:
    - name: health-check-with-curl
      id: test
      uses: Mustafakhn/health-check-action@v2
      with:
          website_url: https://full-cicd.uc.r.appspot.com/
          version_name: version
          method: wget
          timeout: 15
#     - run: |
#         echo "exit_stataus=$exit-status" >> $GITHUB_OUTPUT
#       if: failure()
          
#   notification:
#     runs-on: ubuntu-latest
#     needs: [ test-after-deploying-to-default-with-curl ]
#     if: failure()
#     steps:
#     - name: failure-message
#       run: echo "failure"

    - if: failure()
      name: health-check-with-wget
#       run: echo ${{ steps.test.outputs.exit_status }}
#       uses: Mustafakhn/health-check-action@main
#       with:
#           website_url: https://full-cicd.uc.r.appspot.com/
#           version_name: version
#           method: wget
      run: |
        echo ${{ steps.test.outputs.test-result }}  
  notification-success:
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-curl ]
    if: success()
    steps:
    - name: success-message
      
      run: echo "success"
  
  notification-failure:
    runs-on: ubuntu-latest
    needs: [ test-after-deploying-to-default-with-curl ]
    if: failure()
    
    steps:
    - name: failure-message
      if: failure()
      run: echo "failure"
